create table tb_notes (id int8 generated by default as identity, note_text varchar(255), user_id int8, primary key (id));
create table tb_users (id int8 generated by default as identity, email varchar(255), password varchar(255), primary key (id));
create table tb_users_notes (user_id int8 not null, notes_id int8 not null);
alter table if exists tb_users_notes add constraint UK_hhfa3eg4nkedfpns6b2q89req unique (notes_id);
alter table if exists tb_notes add constraint FK7fvbxc57hl239bxhy7dfg0s7q foreign key (user_id) references tb_users;
alter table if exists tb_users_notes add constraint FK2jvfld2wbn1ltd05lvw6l8mc0 foreign key (notes_id) references tb_notes;
alter table if exists tb_users_notes add constraint FKscks6jd8n4iwb2kcj87wggbo5 foreign key (user_id) references tb_users;
