
spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    username: sa
    password:
  jpa:
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2-console

security:
  oauth2:
    client:
      client-id: notapp-api
      client-secret: notapp$secret$here

jwt:
  secret: $MySecret#NeedChangeHere!!
  duration: 86400